package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

type Tool struct {
	Name        string
	Description string
}

func main() {
	// Find defs.go relative to script location or CWD
	defsPath := findDefsGo()
	if defsPath == "" {
		fmt.Fprintf(os.Stderr, "error: cannot find internal/mcp/defs.go\n")
		os.Exit(1)
	}

	tools := parseTools(defsPath)
	if len(tools) == 0 {
		fmt.Fprintf(os.Stderr, "error: no tools found in %s\n", defsPath)
		os.Exit(1)
	}

	// Group by category
	byCategory := make(map[string][]Tool)
	for _, t := range tools {
		cat := categorizeTool(t.Name)
		byCategory[cat] = append(byCategory[cat], t)
	}

	// Build output
	var b strings.Builder
	b.WriteString(fmt.Sprintf("# Tools (%d)\n\n", len(tools)))
	b.WriteString(fmt.Sprintf("Auto-generated from `internal/mcp/defs.go`. Total: **%d tools**.\n\n", len(tools)))

	// Sort categories
	cats := make([]string, 0, len(byCategory))
	for cat := range byCategory {
		cats = append(cats, cat)
	}
	sort.Strings(cats)

	for _, cat := range cats {
		catTools := byCategory[cat]
		sort.Slice(catTools, func(i, j int) bool {
			return catTools[i].Name < catTools[j].Name
		})
		b.WriteString(fmt.Sprintf("## %s (%d)\n\n", cat, len(catTools)))
		for _, t := range catTools {
			b.WriteString(fmt.Sprintf("- `%s` — %s\n", t.Name, t.Description))
		}
		b.WriteString("\n")
	}

	b.WriteString("<!--\n")
	b.WriteString(fmt.Sprintf("Generated by scripts/gen-tools-doc.go — %d tools found\n", len(tools)))
	b.WriteString("-->\n")

	// Write to docs/
	outputPath := filepath.Join("docs", "reference", "tools.md")
	if err := os.MkdirAll("docs/reference", 0755); err != nil {
		fmt.Fprintf(os.Stderr, "error creating docs/reference: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outputPath, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outputPath, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %s (%d tools)\n", outputPath, len(tools))
}

func categorizeTool(name string) string {
	switch {
	case strings.HasPrefix(name, "store") || strings.HasPrefix(name, "review") || strings.HasPrefix(name, "apply") || strings.HasPrefix(name, "dismiss") || name == "status" || name == "search" || name == "search_memories" || name == "search_skills" || name == "reindex":
		return "Memory"
	case strings.HasPrefix(name, "skills_") || strings.HasPrefix(name, "store_skill") || strings.HasPrefix(name, "list_skill"):
		return "Skills"
	case strings.HasPrefix(name, "persona") || name == "onboard" || name == "list_personas" || name == "switch_persona" || name == "delete_persona":
		return "Persona"
	case strings.HasPrefix(name, "log_interaction") || strings.HasPrefix(name, "evolve") || strings.HasPrefix(name, "consolidate") || strings.HasPrefix(name, "discover_skills") || strings.HasPrefix(name, "evolution_") || strings.HasPrefix(name, "interaction_") || strings.HasPrefix(name, "get_evolved"):
		return "Evolution"
	case strings.HasPrefix(name, "log_tool_gap") || strings.HasPrefix(name, "list_tool_gaps") || strings.HasPrefix(name, "resolve_tool_gap"):
		return "Tool Gaps"
	case strings.HasPrefix(name, "log_tool_knowledge") || strings.HasPrefix(name, "get_tool_knowledge") || strings.HasPrefix(name, "list_tool_knowledge") || strings.HasPrefix(name, "log_tool_recipe") || strings.HasPrefix(name, "get_tool_recipes") || strings.HasPrefix(name, "record_recipe"):
		return "Tool Knowledge"
	case strings.HasPrefix(name, "log_tool_error") || strings.HasPrefix(name, "list_tool_errors") || strings.HasPrefix(name, "resolve_tool_error") || strings.HasPrefix(name, "register_mcp") || strings.HasPrefix(name, "get_mcp") || strings.HasPrefix(name, "list_mcp"):
		return "Error Tracking & MCP"
	default:
		return "Other"
	}
}

func findDefsGo() string {
	candidates := []string{
		filepath.Join("internal", "mcp", "defs.go"),
		filepath.Join("..", "internal", "mcp", "defs.go"),
	}
	for _, c := range candidates {
		if _, err := os.Stat(c); err == nil {
			return c
		}
	}
	return ""
}

func parseTools(path string) []Tool {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error parsing %s: %v\n", path, err)
		os.Exit(1)
	}

	var tools []Tool

	// Walk all variable declarations looking for DefaultTools slice
	for _, decl := range f.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.VAR {
			continue
		}
		for _, spec := range gen.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			if vs.Names[0].Name != "DefaultTools" {
				continue
			}
			// Found DefaultTools — parse the composite literal
			cl, ok := vs.Values[0].(*ast.CompositeLit)
			if !ok {
				continue
			}
			for _, elt := range cl.Elts {
				compLit, ok := elt.(*ast.CompositeLit)
				if !ok {
					continue
				}
				var t Tool
				for _, field := range compLit.Elts {
					kv, ok := field.(*ast.KeyValueExpr)
					if !ok {
						continue
					}
					key, ok := kv.Key.(*ast.Ident)
					if !ok {
						continue
					}
					switch key.Name {
					case "Name":
						t.Name = stringValue(kv.Value)
					case "Description":
						t.Description = stringValue(kv.Value)
					}
				}
				if t.Name != "" {
					tools = append(tools, t)
				}
			}
		}
	}

	return tools
}

func stringValue(expr ast.Expr) string {
	lit, ok := expr.(*ast.BasicLit)
	if !ok {
		return ""
	}
	s, err := strconv.Unquote(lit.Value)
	if err != nil {
		return strings.Trim(lit.Value, "\"")
	}
	return s
}
